# [START runtime]
runtime: python
env: flex
threadsafe: yes
# [END runtime]

env_variables:
  API_KEY: AIzaSyB_7Bxcgo-mCy6RBP4V9HaADW0OYB90p6A

handlers:
- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)
- url: /
  static_files: dist/index.html
  upload: dist/index.html
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

manual_scaling:
  instances: 2